#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Example usage:
# ./Allrun                     -> partitioned (Aitken), serial
# ./Allrun monolithic          -> monolithic (Newton/PETSc), serial

SOLVER="partitioned"

for arg in "$@"
do
    case "$arg" in
        monolithic)
            SOLVER="monolithic"
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: ./Allrun [monolithic]"
            exit 1
            ;;
    esac
done

# Source solids4Foam scripts
source solids4FoamScripts.sh

echo "Compiling membraneRoof2d tutorial libraries"
(cd src && ./Allwmake)

# Restore 0 directory
restore0Dir

# PETSc is required for this case
if [[ -z "${PETSC_DIR:-}" ]]
then
    echo; echo "Skipping this case as PETSc is not installed"
    echo "Please set the PETSC_DIR variable and rebuild solids4foam"; echo
    exit 0
fi

if [[ "$SOLVER" == "monolithic" ]]; then
    solids4Foam::caseDoesNotRunWithFoamExtend
    solids4Foam::caseDoesNotRunWithOpenFOAMOrg
    echo "Using the monolithic Newton/PETSc approach"
    for file in $(find ./0 ./constant ./system -name '*.monolithic')
    do
        ln -vnsf ${file##*/} ${file%.*}
    done
else
    echo "Using partitioned coupling setup"

    # Remove monolithic-only files that may have been copied in from a dirty
    # case tree after a previous monolithic run.
    rm -f \
        0/fluid/D \
        0/fluid/pointD \
        0/fluid/pointDisplacement \
        0/solid/U \
        constant/fluid/mechanicalProperties \
        constant/fluid/solidProperties

    # Create all .partitioned symlinks
    for file in $(find ./0 ./constant ./system -name '*.partitioned')
    do
        ln -vnsf "${file##*/}" "${file%.partitioned}"
    done

    solids4Foam::convertCaseFormat .
fi

# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Refine the fluid mesh
solids4Foam::runApplication -o -s fluid.1 setSet -batch setSet1.batch -region fluid
solids4Foam::runApplication -o -s fluid.1 refineMesh -region fluid -dict ./system/fluid/refineMeshDict.1 -overwrite

solids4Foam::runApplication -o -s fluid.2 setSet -batch setSet2.batch -region fluid
solids4Foam::runApplication -o -s fluid.2 refineMesh -region fluid -dict ./system/fluid/refineMeshDict.2 -overwrite

# Run solver
solids4Foam::runApplication solids4Foam

# Create plots
if command -v gnuplot &> /dev/null
then
    echo "Generating deflection.pdf using gnuplot"
    gnuplot deflection.gnuplot &> /dev/null
    if [ $(find . -name force.dat | wc -l) -eq 1 ]
    then
        echo "Generating force.pdf using gnuplot"
        gnuplot force.gnuplot &> /dev/null
    fi
else
    echo "Please install gnuplot if you would like to generate the plots"
fi
